### ISSUE TITLE
Mixins do not work in dev enviroment

### ISSUE THREAD

**Issue by ScottCowe** [Nessiesson/ForgeMixinExampleMod#1]
I cloned the repo and did not change anything, except the loggers (change to log4j LogManager.getLogger...) and the mixins did not load. Is there a program arg i am not using that i need to? Thanks

**Comment by ScottCowe** [comment]
Fixed: Added `--tweakClass org.spongepowered.asm.launch.MixinTweaker` as program arg and added -`Dfml.coreMods.load=pathtomixinloader` as enviroment arg

**Comment by Nessiesson** [comment]
That should not have been an issue if you let Gradle generate your runconfigs(?). (e.g., `gradle genIntellijRuns`; I am there that there is something similar for Eclipse.)

**Comment by ScottCowe** [comment]
Yeah I ran genIntellijRunsa and no run configs showed up
